name: flutter_annual_task
description: A new Flutter package.
version: 0.0.1
homepage: http://

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: