name: flutter_annual_task
description: A new Flutter package.
version: 0.1.0
homepage: https://github.com/HuanSuh/flutter_annual_task

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: