name: flutter_annual_task
description: Flutter package for displaying grid view of daily task like Github-Contributions(Github calendar).
version: 0.1.4
homepage: https://github.com/HuanSuh/flutter_annual_task

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: